services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: steam_lens
      POSTGRES_PASSWORD: password
      POSTGRES_DB: steam_lens_db
    volumes:
      - psqldata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: steam_lens
      DB_PASSWORD: password
      DB_NAME: steam_lens_db
    env_file:
      - .env
    ports:
      - "8080:8080"
    
  migrate:
    image: golang:1.24.3
    restart: no
    depends_on:
      - db
    volumes:
      - ./sql/schema:/migrations
    working_dir: /migrations
    build:
      context: ./sql/schema
      dockerfile: Dockerfile
    env_file:
      - .env

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  psqldata:
